#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

while [ ! -e ROOT_DEV ]
do
	busybox usleep 50000
done

/bin/tee-supplicant &
key=`/bin/testapp_storage_from_uboot`
busybox killall tee-supplicant

dmsetup create vroot --table "0 SECTORS crypt CIPHER $key 0 ROOT_DEV 0 1 allow_discards"
mount /dev/mapper/vroot /mnt

# busybox echo "Hello Enter Ramdisk Test System"
exec busybox switch_root /mnt /init
# exec /sbin/init "$@"
